# Activate with: ./gradlew run -Dmicronaut.environments=docker
datasources.default.url=jdbc:mysql://localhost:3307/motel_db
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.username=motel_user
datasources.default.password=motel_password
datasources.default.dialect=MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true
jpa.default.entity-scan.packages=com.motel.domain
